<a href="https://colab.research.google.com/github/AbdulMuheetGhouri/Data-Cleaning-and-Data-Assessing/blob/main/Data_Assessing_and_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

patients = pd.read_csv("patients.csv")
treatments = pd.read_csv("treatments.csv")
adverse_reactions = pd.read_csv("adverse_reactions.csv")
treatments_cut = pd.read_csv("treatments_cut.csv")

with pd.ExcelWriter("clinical_trial.xlsx") as writer:
  patients.to_excel(writer, sheet_name="patients", )
  treatments.to_excel(writer, sheet_name="treatments", )
  adverse_reactions.to_excel(writer, sheet_name="adverse_reactions", )
  treatments_cut.to_excel(writer,sheet_name="treatments_cut")

### Issues with the dataset

1. Dirty Data

  Table - `Patients`

    - patient_id = 9 has misspelled name 'Dsvid' instead of David `accuracy issue`
    - state col sometimes contain full name and some times abbrivietation `consistency issue`
    - zip code col has entries with 4 digit `validity issue`
    - data missing for 12 patients in address,city,	state,zip_code	,country,	contact `completion issue`
    - incorrect data type assigned to sex, zip code, birthdate `validity`
    - duplicate entries by the name of John Doe `accuracy issue`
    - one patient has weight = 48 pounds `accuracy issue`
    - one patient has height = 27 inches `accuracy issue`

  Table - `Treatments` & `Treatments_cut`

    - given_name and surname col is is all lower case `consistency issue`
    - remove u from Auralin and Novadra cols `validity issue`
    - '-' in novadra and Auralin col treated as nan `validity issue`
    - missing values in hba1c_change col `completion issue`
    - 1 duplicate entry by the name Joseph day `accuracyissue`
    - in hba1c_change 9 instead of 4 `accuracy issue`

  Table - `Adverse_reactions`

    - given_name and surname are all in lower case `consistency issue`

2. Messy Data

  Table - `Patients`

    - contact col contains both phone and email

  Table - `Treatments` & `Treatments_cut`

    - Auralin and Novadra col should be split into 2 cols start and end dose
    - merge both the tables

  Table - `Adverse_reactions`

    - This table should not exist independently

*Automatic Assessment*

#Data Cleaning Order:
---
1. Quality - `Completeness`
2. Tidiness
3. Quality - `Validity`
4. Quality - `Accuracy`
5. Quality - `Consistency`

In [2]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [3]:
patients.tail()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [4]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

In [5]:
patients.sample()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
284,285,male,Nilton,Quintanilla,4038 Farland Street,Walpole,MA,2081.0,United States,774-219-3140NiltonQuintanillaAlmonte@rhyta.com,2/9/1980,186.3,75,23.3

In [6]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [7]:
patients[patients.isnull().any(axis=1)]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [8]:
adverse_reactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 948.0+ bytes

In [9]:
patients.duplicated().sum()

np.int64(0)

In [10]:
patients['patient_id'].duplicated().sum()

np.int64(0)

In [11]:
patients[patients.duplicated(subset=['given_name','surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [12]:
treatments[treatments.duplicated()]
treatments[treatments.duplicated(subset=['given_name','surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [13]:
treatments_cut[treatments_cut.duplicated()]
# treatments[treatments.duplicated(subset=['given_name','surname'])]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [14]:
adverse_reactions[adverse_reactions.duplicated()]
adverse_reactions[adverse_reactions.duplicated(subset=['given_name','surname'])]

Empty DataFrame
Columns: [given_name, surname, adverse_reaction]
Index: []

In [15]:
patients[patients['height'] == 27]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

### Copying the DataFrames.

In [16]:
patients_df = patients.copy()
treatments_df = treatments.copy()
adverse_reactions_df = adverse_reactions.copy()
treatments_cut_df = treatments_cut.copy()

###Define.
> Table: 'patients_df'
- replace missing columns with `no data available` string.
- we have to apply regex to split email and phone number.
```
#Code
- patients_df.fillna("no data available",inplace=True)
#Test
- patients_df.info()
```


---
> Table: 'treatments & treatments_cut'
- filled hba1c_change by subtracting hba1c_end from	hba1c_start.
```
#Code
- treatments['hba1c_change'] = treatments['hba1c_start'] - treatments['hba1c_end']
- treatments_cut_df['hba1c_change'] = treatments_cut_df['hba1c_start'] - treatments_cut_df['hba1c_end']


#Test
- treatments_cut_df.info()
- treatments_df.info()
```

In [17]:
patients_df['phone'] = patients_df['contact'].str.replace(r'[^\d]', '', regex=True)
patients_df['email'] = patients_df['contact'].str.extract(r'([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})')

In [18]:
# 1. Extract the email address
patients_df['email'] = patients_df['contact'].str.extract(r'([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})')

# 2. Extract the phone number (captures optional country code and various phone formats)
# patients_df['phone'] = patients_df['contact'].str.extract(r'((?:\+?\d{1,2}\s*)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})')

# 3. (Optional) Drop the original contact column
# patients_df.drop(columns=['contact'], inplace=True)

In [19]:
patients_df.sample(5)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,phone,email
205,206,male,Breno,Correia,3539 Bottom Lane,Tonawanda,New York,14150.0,United States,716-743-5884BrenoLimaCorreia@superrito.com,7/11/1974,180.6,67,28.3,7167435884,716-743-5884BrenoLimaCorreia@superrito.com
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6,2074770579,207-477-0579MustafaLindstrom@jourrapide.com
136,137,female,Victoria,Mikkelsen,2121 Liberty Avenue,Los Angeles,California,90017.0,United States,714-507-4204VictoriaTMikkelsen@armyspy.com,5/7/1925,179.3,63,31.8,7145074204,714-507-4204VictoriaTMikkelsen@armyspy.com
479,480,male,Tapa,Arsanukayev,4720 Gordon Street,Ontario,California,91762.0,United States,TapaArsanukayev@dayrep.com1 909 458 2515,9/15/1955,220.0,65,36.6,19094582515,TapaArsanukayev@dayrep.com
105,106,male,Nate,Bowden,4310 Johnson Street,Clinton,NC,28328.0,United States,NateBowden@einrot.com919-915-8670,3/26/1954,222.0,71,31.0,9199158670,NateBowden@einrot.com

In [20]:
treatments_df = treatments_df.melt(id_vars=['given_name'	,'surname','hba1c_start'	,'hba1c_end',	'hba1c_change'],var_name="type",value_name= "dosage_range")

In [21]:
treatments_df = treatments_df[treatments_df['dosage_range'] != '-']

In [22]:
treatments_df['dosage_Start'] =  treatments_df['dosage_range'].str.split("-").str.get(0)
treatments_df['dosage_End'] = treatments_df['dosage_range'].str.split("-").str.get(1)

In [23]:
treatments_df['dosage_Start'] = treatments_df['dosage_Start'].str.replace("u","")
treatments_df['dosage_End'] = treatments_df['dosage_End'].str.replace("u","")

In [24]:
treatments_df['dosage_Start']= treatments_df['dosage_Start'].astype("int")
treatments_df['dosage_End'] = treatments_df['dosage_End'].astype("int")

In [25]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 280 entries, 0 to 556
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   hba1c_start   280 non-null    float64
 3   hba1c_end     280 non-null    float64
 4   hba1c_change  171 non-null    float64
 5   type          280 non-null    object
 6   dosage_range  280 non-null    object
 7   dosage_Start  280 non-null    int64
 8   dosage_End    280 non-null    int64
dtypes: float64(3), int64(2), object(4)
memory usage: 21.9+ KB

In [26]:
treatments_df =treatments_df.merge(adverse_reactions_df,how="left",on=["given_name","surname"])

In [27]:
treatments_df['adverse_reaction'] =  treatments_df['adverse_reaction'].fillna("no adverse reaction")

In [28]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range,dosage_Start,dosage_End,adverse_reaction
0,veronika,jindrová,7.63,7.20,NaN,auralin,41u - 48u,41,48,no adverse reaction
1,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u,33,36,no adverse reaction
2,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u,37,42,no adverse reaction
3,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u,31,38,no adverse reaction
4,asia,woźniak,7.76,7.37,NaN,auralin,30u - 36u,30,36,no adverse reaction
...,...,...,...,...,...,...,...,...,...,...
275,yasmin,araujo,7.82,7.36,0.96,novodra,51u - 54u,51,54,no adverse reaction
276,hiromu,horikawa,7.77,7.28,NaN,novodra,47u - 46u,47,46,no adverse reaction
277,leo,vieira,7.74,7.36,NaN,novodra,30u - 33u,30,33,no adverse reaction
278,steven,roy,7.87,7.43,0.94,novodra,41u - 43u,41,43,headache
279,john,teichelmann,7.90,7.58,NaN,novodra,49u - 49u,49,49,no adverse reaction